pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    postImage:
                        items:
                            -
                                method: scaleByHeight
                                arguments:
                                    height: 300
                                    forceResize: false
                        medias: {  }
                        name: postImage
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1657752072
                        creationDate: 1657751976
                        preserveAnimation: false
